### ISSUE TITLE
Issue with the python version

### ISSUE THREAD

**Issue by waseemfa** [nmondal/pyunitperf#1]
There seems to be an issue with the python version if it is below 2.7.

Attaching a snippet of the issue

```
Exception in thread Thread-4:
Traceback (most recent call last):
File "/opt/python/python-2.6/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
self.run()
File "/opt/python/python-2.6/lib64/python2.6/threading.py", line 484, in run
self.__target(*self.__args, **self.__kwargs)
File "/user/pyunitperf-master/ThreadedTest.py", line 70, in __call__
self.test.run(self.result)
File "/user/pyunitperf-master/RepeatedTest.py", line 27, in run
TestDecorator.run(self, result)
File "/user/pyunitperf-master/TestDecorator.py", line 27, in run
self.basicRun(result)
File "/user/pyunitperf-master/TestDecorator.py", line 21, in basicRun
self.test.run(result)
AttributeError: 'HierarchicalConfiguration' object has no attribute 'run'
```

**Comment by nmondal** [comment]
You are using the wrong test. You should use the [TestCaseWithParameters](https://github.com/nmondal/pyunitperf/blob/master/TestCaseWithParameters.py) as base line.
Please let me know if you are successful in  running it.
